# -*- coding: utf-8 -*-
"""rdflib_syntax_check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eylVcbxjVHCCOdO06Jg1EjxZgJK6KbBE
"""

!pip install rdflib

from rdflib import Graph
turtle_data = """
     @prefix ex: <http://example.org/> .
     ex:subject ex:predicate "object.  # Missing closing quotation mark

"""

g = Graph()

try:
    g.parse(data=turtle_data, format="turtle")
    print("Turtle syntax is correct.")
except Exception as e:  # This catches any exception, including BadSyntax and ParserError
    print(f"Error parsing Turtle file: {e}")

from rdflib import Graph
turtle_data = """
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix wine: <http://example.org/wine#> .

# Classes
wine:Wine rdf:type owl:Class .
wine:RedWine rdf:type owl:Class ; rdfs:subClassOf wine:Wine .
wine:WhiteWine rdf:type owl:Class ; rdfs:subClassOf wine:Wine .
wine:RoseWine rdf:type owl:Class ; rdfs:subClassOf wine:Wine .
wine:SparklingWine rdf:type owl:Class ; rdfs:subClassOf wine:Wine .
wine:DessertWine rdf:type owl:Class ; rdfs:subClassOf wine:Wine .
wine:FortifiedWine rdf:type owl:Class ; rdfs:subClassOf wine:Wine .
wine:GrapeVariety rdf:type owl:Class .
wine:FlavorProfile rdf:type owl:Class .
wine:BodyType rdf:type owl:Class .
wine:SweetnessLevel rdf:type owl:Class .
wine:AcidityLevel rdf:type owl:Class .
wine:TanninLevel rdf:type owl:Class .
wine:AlcoholContent rdf:type owl:Class .
wine:WineType rdf:type owl:Class .
wine:Characteristics rdf:type owl:Class .
wine:WineProducingRegion rdf:type owl:Class .
wine:Climate rdf:type owl:Class .
wine:WineCharacteristic rdf:type owl:Class .
wine:WineMakingProcess rdf:type owl:Class .
wine:WinemakingTechnique rdf:type owl:Class .
wine:AromaDescriptor rdf:type owl:Class .
wine:FlavorDescriptor rdf:type owl:Class .
wine:VisualCharacteristic rdf:type owl:Class .
wine:Food rdf:type owl:Class .
wine:TastePreference rdf:type owl:Class .
wine:History rdf:type owl:Class .

# Properties
wine:hasGrapeVariety rdf:type owl:ObjectProperty .
wine:hasFlavorProfile rdf:type owl:ObjectProperty .
wine:hasBody rdf:type owl:ObjectProperty .
wine:hasSweetnessLevel rdf:type owl:ObjectProperty .
wine:hasAcidityLevel rdf:type owl:ObjectProperty .
wine:hasTanninLevel rdf:type owl:ObjectProperty .
wine:hasAlcoholContent rdf:type owl:DatatypeProperty .
wine:isTypicallyUsedFor rdf:type owl:ObjectProperty .
wine:hasCharacteristic rdf:type owl:ObjectProperty .
wine:isProducedIn rdf:type owl:ObjectProperty .
wine:affects rdf:type owl:ObjectProperty .
wine:comprisesSteps rdf:type owl:ObjectProperty .
wine:hasAroma rdf:type owl:ObjectProperty .
wine:hasFlavor rdf:type owl:ObjectProperty .
wine:hasVisualCharacteristic rdf:type owl:ObjectProperty .
wine:isPairedWith rdf:type owl:ObjectProperty .
wine:hasPreference rdf:type owl:ObjectProperty .
wine:matchesPreference rdf:type owl:ObjectProperty .
wine:hasOrigin rdf:type owl:ObjectProperty .
"""

g = Graph()

try:
    g.parse(data=turtle_data, format="turtle")
    print("Turtle syntax is correct.")
except Exception as e:  # This catches any exception, including BadSyntax and ParserError
    print(f"Error parsing Turtle file: {e}")

